/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Citizen = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'badgeLevel' : IDL.Text,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'trustScore' : IDL.Nat,
  'endorsementCount' : IDL.Nat,
  'distance' : IDL.Nat,
  'skill' : IDL.Text,
  'videoURL' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const LearningRequest = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
  'requesterId' : IDL.Text,
  'targetUserId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
});
export const CertificationResult = IDL.Record({
  'workerId' : IDL.Nat,
  'level' : IDL.Text,
  'issuedDate' : Time,
  'skill' : IDL.Text,
  'certificateId' : IDL.Text,
  'mcqScore' : IDL.Nat,
  'practicalPassed' : IDL.Bool,
  'passed' : IDL.Bool,
});
export const PracticalVideoSubmission = IDL.Record({
  'status' : IDL.Text,
  'workerId' : IDL.Nat,
  'videoDataURI' : IDL.Text,
  'submittedAt' : Time,
  'skill' : IDL.Text,
  'workerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePracticalVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'endorseUser' : IDL.Func([IDL.Nat], [], []),
  'findCitizenByName' : IDL.Func([IDL.Text], [IDL.Opt(Citizen)], ['query']),
  'findWorkerByName' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalWorkers' : IDL.Nat,
          'totalCitizens' : IDL.Nat,
          'totalCertified' : IDL.Nat,
          'totalRequests' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllCitizens' : IDL.Func([], [IDL.Vec(Citizen)], ['query']),
  'getAllLearningRequests' : IDL.Func(
      [],
      [IDL.Vec(LearningRequest)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertification' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CertificationResult)],
      ['query'],
    ),
  'getLearningRequestsForWorker' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LearningRequest)],
      ['query'],
    ),
  'getPendingPracticalVideos' : IDL.Func(
      [],
      [IDL.Vec(PracticalVideoSubmission)],
      ['query'],
    ),
  'getPracticalVideoStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByDistance' : IDL.Func([IDL.Nat], [IDL.Vec(User)], ['query']),
  'getUsersBySkill' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'getWorkerStats' : IDL.Func([IDL.Nat], [User], ['query']),
  'getWorkerVideo' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'loginCitizen' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Citizen)],
      ['query'],
    ),
  'loginWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], ['query']),
  'registerCitizen' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'registerWorker' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'rejectPracticalVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveWorkerVideo' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'submitLearningRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'submitPracticalVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitTestResult' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Citizen = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'badgeLevel' : IDL.Text,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'trustScore' : IDL.Nat,
    'endorsementCount' : IDL.Nat,
    'distance' : IDL.Nat,
    'skill' : IDL.Text,
    'videoURL' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const LearningRequest = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
    'requesterId' : IDL.Text,
    'targetUserId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
  });
  const CertificationResult = IDL.Record({
    'workerId' : IDL.Nat,
    'level' : IDL.Text,
    'issuedDate' : Time,
    'skill' : IDL.Text,
    'certificateId' : IDL.Text,
    'mcqScore' : IDL.Nat,
    'practicalPassed' : IDL.Bool,
    'passed' : IDL.Bool,
  });
  const PracticalVideoSubmission = IDL.Record({
    'status' : IDL.Text,
    'workerId' : IDL.Nat,
    'videoDataURI' : IDL.Text,
    'submittedAt' : Time,
    'skill' : IDL.Text,
    'workerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePracticalVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'endorseUser' : IDL.Func([IDL.Nat], [], []),
    'findCitizenByName' : IDL.Func([IDL.Text], [IDL.Opt(Citizen)], ['query']),
    'findWorkerByName' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalWorkers' : IDL.Nat,
            'totalCitizens' : IDL.Nat,
            'totalCertified' : IDL.Nat,
            'totalRequests' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllCitizens' : IDL.Func([], [IDL.Vec(Citizen)], ['query']),
    'getAllLearningRequests' : IDL.Func(
        [],
        [IDL.Vec(LearningRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertification' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CertificationResult)],
        ['query'],
      ),
    'getLearningRequestsForWorker' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LearningRequest)],
        ['query'],
      ),
    'getPendingPracticalVideos' : IDL.Func(
        [],
        [IDL.Vec(PracticalVideoSubmission)],
        ['query'],
      ),
    'getPracticalVideoStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByDistance' : IDL.Func([IDL.Nat], [IDL.Vec(User)], ['query']),
    'getUsersBySkill' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'getWorkerStats' : IDL.Func([IDL.Nat], [User], ['query']),
    'getWorkerVideo' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'loginCitizen' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Citizen)],
        ['query'],
      ),
    'loginWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(User)], ['query']),
    'registerCitizen' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'registerWorker' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'rejectPracticalVideo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveWorkerVideo' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'submitLearningRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'submitPracticalVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitTestResult' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };